baseURL = "https://abarciauskas-bgse.github.io/datafortheclimate/"
languageCode = "en-us"
title = "Data for the Climate"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Data for the Climate"
author = "Aimee Barciauskas"
description = "Exploring data and technology in search of answers to climate questions."
profilePicture = "images/profile.jpg"
keywords = ""
customCss = []
customJs = []
mainSections = ["posts"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/_aimeeb"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/abarciauskas/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/abarciauskas-bgse"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/abarciauskas/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:barciaai@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
